# S3
s3:
  url: "http://127.0.0.1:9000"
  bucket: "test_bucket"
  client_connection_timeout_seconds: 300
# Redis
redis:
  host: "127.0.0.1"
  port: "6379"
  poll_delay_ms: 500
  read_delay_ms: 1000
  queues:
    inbox: "inbox_queue"
    outbox: "outbox_queue"
# Kafka
kafka:
  group_id: "test_group"
  batch_size: 1
  bootstrap_servers: [ "127.0.0.1:9092" ]
  topics:
    input: "test_input_topic"
    output: "test_output_topic"
# Logging
logging:
  log_level: "DEBUG"
